### ISSUE TITLE
Feature request: custom layout file support

### ISSUE THREAD

**Issue by LB--** [CodeDocs/CodeDocs#2]
From https://github.com/mosra/magnum/issues/113#issuecomment-199220264

> custom layout files to work around some rough edges

For example, in Magnum's Doxyfile is [this](https://github.com/mosra/magnum/blob/1f0617ac2798ba995fdd0d176cf1c3f6a1e3106b/Doxyfile#L727-L731), which results in [this file](https://github.com/mosra/magnum/blob/1f0617ac2798ba995fdd0d176cf1c3f6a1e3106b/DoxygenLayout.xml) being used.

[Relevant Doxygen documentation](https://www.stack.nl/~dimitri/doxygen/manual/customize.html#layout)

**Comment by paulnovo** [comment]
@LB--  I think this is already working if you use the default name for the layout file (DoxygenLayout.xml), which you are in morsa/magnum. I just forked magnum and ran it on codedocs. The first line of the log confirms it found and parsed DoxygenLayout.xml. Could you look at the generated [documentation](https://codedocs.xyz/CodeDocs/magnum) to confirm it works? I am not sure what customizations there are in your DoxygenLayout.xml.

**Comment by mosra** [comment]
@paulnovo confirming that the layout file is working, yes (and wow, didn't expect such first-class support :)).

However, it seems that actually the `Doxyfile` was ignored (because I am disabling all graphs, implicit references, adding custom commands etc. and the documentation looks way different when the file is used). Is it by design? .. (Should I open another issue for this?)

**Comment by paulnovo** [comment]
@mosra Great, glad to here it worked. I will mark this closed.

Yes, ignoring the Doxyfile is by design. Partly because these could be named anything and be anywhere, and alot of times they are generated (ie, I use cmake to create the doxyfile). And partly because I want to limit the available options at the moment. But, you can create a .codedocs file in your repository. This file has a subset of the doxygen options. If you login to codedocs, you will see instructions on how to add this file, and the options available.

Please open an issue if there is a Doxygen config option you would like supported in the .codedocs file and I'll look into it. Thanks!

**Comment by mosra** [comment]
I think a better option would be to use the include feature of Doxyfiles -- you can include the project-specific one and then reset all the options to default except those few that you want to support.

Because, at least for my project, you would need to add >30 options to codedocs, because I use literally everything.

**Comment by paulnovo** [comment]
@mosra Sounds good, I added a new issue to for this. #3
