### ISSUE TITLE
Feature request: Includes in .codedocs file

### ISSUE THREAD

**Issue by paulnovo** [CodeDocs/CodeDocs#3]
Allow setting a separate file to include for doxygen settings. Often projects already have a doxyfile somewhere. With this option you could just set the location of this file, instead of duplicating the settings in the .codedocs file.

**Comment by mosra** [comment]
To clarify my initial idea, the workflow could be like this: 

The `.codedocs` conifg would contain just a path to the Doxyfile (and optionally the remaining options for backwards compatibility), say:

```
DOXYFILE = MyDoxyfile
PROJECT_NAME = MyProject
FILE_PATTERNS = *.h
...
```

Which will be converted with the codedocs processor into a real Doxyfile that includes the original file, sets the options _and then_ overrides the options from the original Doxyfile that are useless/harmful for your server, e.g. generating huge PDF output, PNG inheritance graphs etc.

```
# Doxyfile.codedocs
@INCLUDE = MyDoxyfile
PROJECT_NAME = MyProject
FILE_PATTERNS = *.h

# Overrides
HAVE_DOT = NO
GENERATE_HTML = YES
GENERATE_HTMLHELP = NO
GENERATE_LATEX = NO
GENERATE_RTF = NO
...
```

**Comment by paulnovo** [comment]
@mosra I added the DOXFILE option, that will include doxygen settings from another file in the repository. You can see it at work on my [Kodi fork](https://codedocs.xyz/CodeDocs/xbmc/), and it's [.codedocs config](https://github.com/CodeDocs/xbmc/blob/master/.codedocs). You will also notice that I added support for a bunch of the yes/no options requested in #5. Could you test it out and let me know if it works for you.

**Comment by MarkCallow** [comment]
I tried this. It has several problems:
1. It ignores the INPUT specified in the referenced config file and scans every file in the repo.
2. It is generating a very different tree view to what I get when I build manually with the same config file. Below are the tree views from codedocs and my manual build.
   
   | CodeDocs | Manual Build |
   | --- | --- |
   | ![screen shot 2016-05-11 at 2 48 25 pm](https://cloud.githubusercontent.com/assets/2244683/15171200/68ac2756-1787-11e6-9578-443bfc49d182.png) | ![screen shot 2016-05-11 at 2 44 54 pm](https://cloud.githubusercontent.com/assets/2244683/15171153/149b1dde-1787-11e6-8cc8-49aa64530e24.png) |
   
   Some of these differences (e.g. README) are because the files are not being excluded (i.e. INPUT is ignored). Some of them, e.g. presence of the Class hierarchy, I don't understand. Note that my .codedocs has additional EXCLUDES and EXCLUDE_PATTERNS in an attempt to workaround no. 1 above. The list is not quite complete (e.g. README.md is not in it) but also files that should be excluded, e.g "About the GLEW debug libraries" which is from a file in other_libs are being included.
3. Several of the links, e.g. "About the GLEW debug libraries" give not found errors when you click them. These all seem to be files or directories that should have been excluded.

The project is at https://github.com/msc-/KTX. The most recent CodeDocs documentation build is at https://codedocs.xyz/msc-/KTX/.

**Comment by MarkCallow** [comment]
I suspect Classes are not in my manually generated docs because I have OPTIMIZE_OUTPUT_FOR_C = YES. I have included that in my list of config requests in issue #9.

**Comment by paulnovo** [comment]
@msc- Could you refresh the webpage on codedocs? I get something different than you, which is closer to your _Manual Build_ above,  but not perfect:

![snapshot8](https://cloud.githubusercontent.com/assets/1461767/15183686/27c15c74-1760-11e6-96c6-bb93ef0b9758.png)

I think your EXCLUDES are working (please verify), what isn't working is browser caching of webpages. :-(

**Comment by MarkCallow** [comment]
I had already closed the tab so I opened the docs again in a new one. Indeed it looks much better. The remaining differences are from the files I have not yet included in EXCLUDES and the presence of Classes which, as I wrote, I suspect is related to you not having implemented OPTIMIZE_OUTPUT_FOR_C.

**Comment by MarkCallow** [comment]
There is another difference, in the License text. I am investigating. It does not appear to be related to the EXCLUDES issue though.

**Comment by paulnovo** [comment]
This has been added, and seems to be working. I am closing this issue.
